# Generated by Django 3.2 on 2022-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220914_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('admin', 'Admin')], default='STUDENT', max_length=11),
        ),
    ]
